name: Build
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  XCODE_SCHEME: Spices
  BUILD_DESTINATION: platform=iOS Simulator,name=iPhone 16,OS=18.2
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build-for-testing\
            -scheme ${{ env.XCODE_SCHEME }}\
            -sdk iphonesimulator\
            -destination "${{ env.BUILD_DESTINATION }}"\
          | xcbeautify --renderer github-actions
