name: Build Documentation
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build Documentation
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Documentation
        run: |
          set -o pipefail &&\
          xcodebuild docbuild\
            -scheme Spices\
            -destination 'generic/platform=iOS'\
            -derivedDataPath .derived-data\
          | xcbeautify --renderer github-actions
