name: Build Example Project
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  XCODE_PROJECT_PATH: Examples/Example.xcodeproj
  SWIFTUI_XCODE_SCHEME: SwiftUIExample
  UIKIT_XCODE_SCHEME: UIKitExample
  BUILD_DESTINATION: platform=iOS Simulator,name=iPhone 16,OS=18.1
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
jobs:
  build_swiftui:
    name: Build SwiftUI Example Project
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build\
            -project ${{ env.XCODE_PROJECT_PATH }}\
            -scheme ${{ env.SWIFTUI_XCODE_SCHEME }}\
            -sdk iphonesimulator\
            -destination "${{ env.BUILD_DESTINATION }}"\
          | xcbeautify --renderer github-actions
  build_uikit:
    name: Build UIKit Example Project
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build\
            -project ${{ env.XCODE_PROJECT_PATH }}\
            -scheme ${{ env.UIKIT_XCODE_SCHEME }}\
            -sdk iphonesimulator\
            -destination "${{ env.BUILD_DESTINATION }}"\
          | xcbeautify --renderer github-actions
