name: Build Documentation
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build Documentation
    runs-on: macos-15
    continue-on-error: true
    strategy:
      matrix:
        include:
          - xcode: 16.2
          - xcode: 15.4
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Documentation
        run: |
          set -o pipefail &&\
          xcodebuild docbuild\
            -scheme Spices\
            -destination 'generic/platform=iOS'\
            -derivedDataPath .derived-data\
          | xcbeautify --renderer github-actions
