name: SwiftLint
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: SwiftLint
        uses: shapehq/actions/swiftlint@main
        with:
          args: --strict
