name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
jobs:
  run-tests:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -o pipefail &&\
          xcodebuild -scheme Spices test\
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2"\
          | xcbeautify --renderer github-actions
