name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    name: Run Tests
    runs-on: shape
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -o pipefail &&\
          xcodebuild -scheme SHPSpices test\
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"\
          | xcbeautify --renderer github-actions
