name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
permissions: read-all
env:
  XCODE_SCHEME: Spices
jobs:
  run-tests:
    name: Run Tests
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - xcode: 26.0
            destination: iPhone 16 Pro
            os: 26.0
          - xcode: 16.4
            destination: iPhone 16 Pro
            os: 18.5
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -o pipefail &&\
          xcodebuild -scheme ${{ env.XCODE_SCHEME }} test\
            -destination "platform=iOS Simulator,name=${{ matrix.destination }},OS=${{ matrix.os }}"\
          | xcbeautify --renderer github-actions
