name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    name: Run Tests
    runs-on: shape
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        run: swift test 2>&1 | xcbeautify --renderer github-actions
