name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
permissions: read-all
env:
  XCODE_SCHEME: Spices
  BUILD_DESTINATION: platform=iOS Simulator,name=iPhone 16,OS=18.2
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
jobs:
  run-tests:
    name: Run Tests
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -o pipefail &&\
          xcodebuild -scheme ${{ env.XCODE_SCHEME }} test\
            -destination "${{ env.BUILD_DESTINATION }}"\
          | xcbeautify --renderer github-actions
